tree: import latest changes

diff --git a/dot_local/bin/executable_git-log-interactive b/dot_local/bin/executable_git-log-interactive
--- a/dot_local/bin/executable_git-log-interactive
+++ b/dot_local/bin/executable_git-log-interactive
@@ -1,6 +1,36 @@
 #!/bin/bash
 set -euo pipefail
 
+## Navigation:
+## 
+## Select up/down                   Ctrl-K, Ctrl-J
+## Scroll commits up/down           Ctrl-U, Ctrl-D
+## Scroll preview up/down           Alt-U, Alt-D
+## Scroll preview up/down one line  Alt-Y, Alt-E
+## Clear query                      Ctrl-Space
+## Go to top                        Backspace (on empty query)
+## 
+## Git operations:
+## 
+## View commit          Enter
+## Edit commit message  Ctrl-R
+## Delete top commit    Ctrl-X
+## Rebase on commit     Ctrl-B
+## Reload log           Ctrl-S
+## 
+## Browser:
+## 
+## Open PR in browser      Ctrl-P
+## Open commit in browser  Ctrl-O
+## 
+## Misc:
+## 
+## Show this help                         F1
+## Change preview location                F2
+## Toggle preview                         Ctrl-/
+## Edit files in commit                   Ctrl-H
+## Copy commit hashes to tmux and stdout  Ctrl-G
+
 # Based on https://github.com/junegunn/fzf.vim/issues/211#issuecomment-497943378.
 # Some explanations:
 #  - The `-d '\x00' --nth 4,6` is to only search within the author and commit
@@ -10,17 +40,49 @@ set -euo pipefail
 #  - The `ctrl-r:+reload` syntax means that the binding is additive rather
 #    than replacing (after editing the commit message, we want to reload).
 
-export FZF_DEFAULT_COMMAND="git log --graph --pretty=format:'%C(yellow)%x00%h%x00 %Cred%ad %x00%Cblue%an%Cgreen%x00%d %x00%Creset%s' --date=short --color=always $@"
-fzf --ansi --no-sort --reverse --tiebreak=index -d '\x00' --nth 4,6  \
-  --header 'View: Enter | Reload: C-S | Reload at commit: C-Space | Edit files: C-H | Edit commit: C-R | Rebase: Ctrl-B' \
-  --preview '[ -z {2} ] || git show --color=always {2}' \
+if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]; then
+    echo "error: not inside a git repo" >&2
+    exit 1
+fi
+
+graph=(--graph)
+if [ -n "${NO_GRAPH:-}" ]; then
+    graph=()
+fi
+
+extra_args=()
+while [ $# -gt 0 ]; do
+    extra_args+=("$(printf '%q' "$1")")
+    shift
+done
+export FZF_DEFAULT_COMMAND="git log ${graph[*]} --pretty=format:'%C(yellow)%x00%h%x00 %Cred%ad %x00%Cblue%an%Cgreen%x00%d %x00%Creset%s' --date=short --color=always ${extra_args[*]}"
+
+tmux=true
+if [ -n "${TMUX:-}" ]; then
+    tmux=tmux
+fi
+
+## --header 'View: Enter | Reload: C-S | Edit files: C-H | Edit commit: C-R | Help: F1' \
+
+# shellcheck disable=SC2016
+fzf --track --ansi --no-sort --reverse --tiebreak=index -m -d '\x00' --nth 4,6  \
+  --preview '[ -z {2} ] || git show --color=always {2} | delta' \
+  --bind 'f2:change-preview-window(down|right)' \
   --bind 'ctrl-d:half-page-down,ctrl-u:half-page-up' \
   --bind 'alt-e:preview-down,alt-y:preview-up,alt-d:preview-half-page-down,alt-u:preview-half-page-up' \
-  --bind 'enter:execute([ -z {2} ] || git show --color=always {2} | less -R)' \
-  --bind 'ctrl-space:execute([ -z {2} ] || git lgi {2})' \
+  --bind 'enter:execute([ -z {2} ] || git show --color=always {2} | delta | less -R)' \
+  --bind 'ctrl-space:clear-query' \
+  --bind 'backward-eof:first' \
   --bind 'ctrl-h:execute([ -z {2} ] || git edit {2})' \
   --bind 'ctrl-r:execute([ -z {2} ] || git reword {2})' \
   --bind "ctrl-r:+reload:${FZF_DEFAULT_COMMAND}" \
   --bind 'ctrl-b:execute([ -z {2} ] || git rebase -i {2})' \
   --bind "ctrl-b:+reload:${FZF_DEFAULT_COMMAND}" \
-  --bind "ctrl-s:reload:${FZF_DEFAULT_COMMAND}"
+  --bind 'ctrl-x:execute([ -z {2} ] || git nuke)' \
+  --bind "ctrl-x:+reload:${FZF_DEFAULT_COMMAND}" \
+  --bind "ctrl-s:reload:${FZF_DEFAULT_COMMAND}" \
+  --bind "ctrl-g:become:$tmux set-buffer '{+2}' && echo {+2}" \
+  --bind 'ctrl-p:execute-silent:[ -z {2} ] || (url=$(git get-pr-for-commit {2}) && ${container:+flatpak-spawn --host} /usr/bin/xdg-open ${url})' \
+  --bind 'ctrl-o:execute-silent:[ -z {2} ] || (url=$(git commitlink {2}) && ${container:+flatpak-spawn --host} /usr/bin/xdg-open ${url})' \
+  --bind "f1:execute(grep '^## ' '$0' | cut -f2- -d' ' | less)" \
+  --bind "ctrl-/:toggle-preview"
